### ISSUE TITLE
Managing recurring reminders

### ISSUE THREAD

**Issue by addykim** [TexasLAN/LANBot#147]
As far as I know, there isn't a way to set a recurring reminder. This would be super useful for the house members especially (e.g. taking out the trash) or for active members.

Use cases:
- House members - reminder to take out the trash and using thread feature in slack to mark as done
- General membership - Update calendar for location changes, etc. Lanbot reminds general membership that meetings are happening. 

I think this could help centralize some of the information since people seem to prefer reading slack or even use slack for ~cal rather than syncing the calendar to their own calendar app.

Potential usage:
`lanbot remind me every <time period> to do <action>`
 OR
remind based on google calendar events, similar to google calendar notification system

**Comment by stevendiaz** [comment]
https://slackhq.com/getting-things-done-with-reminders-9bdb7686b57a

`/remind me "Take out the trash" every Friday`

**Comment by addykim** [comment]
Oh sweet. We'll use that.

**Comment by addykim** [comment]
This actually solves what I was requesting better https://slackhq.com/google-calendar-reminders-come-to-slack-8b8c515bfe87

**Comment by stevendiaz** [comment]
I like this integration better. It's more customizable.
