### ISSUE TITLE
Album of the week

### ISSUE THREAD

**Issue by rob0rt** [TexasLAN/LANBot#4]
Create something for AOTW that implemented the following:

```
aotw nominate [spotify uri/ url] - nominate an album
aotw nominations - view all current nominations
aotw select [nomination index] - select the AOTW and reset nominations
aotw history - view all historical aotws
aotw current - view the current aotw
```

**Comment by ThomasGaubert** [comment]
@DrewRomanyk This can be closed now.

**Comment by rob0rt** [comment]
Apparently I can close it since I made it or something.
![iyoxpb3](https://cloud.githubusercontent.com/assets/3067060/7505598/18a04382-f41a-11e4-9b29-e00d574c6e7e.gif)
