### ISSUE TITLE
GH webhooks

### ISSUE THREAD

**Issue by arrdem** [TexasLAN/LANBot#61]
https://github.com/hubot-scripts/hubot-github-repo-event-notifier

lanbot should post to #projects whenever there's a new issue opened on any of the texaslan repos, or when a PR is opened. This should save people messaging me and Drew "peep my PR" over and over.

**Comment by stevendiaz** [comment]
peep my pr tho :eyes:

**Comment by aaaanderson** [comment]
#projects is a pretty busy channel, what about #bots

**Comment by arrdem** [comment]
I think #projects is appropriate especially since this is gonna be Omega messages and soforth not just random lanbot updates.

**Comment by coltwhaley** [comment]
so this can be closed now that we added the slack integration
