### ISSUE TITLE
Not a fan

### ISSUE THREAD

**Issue by clairebingham** [TexasLAN/LANBot#69]
I hate this response. We should get rid of it. IDK how tho

**Comment by clairebingham** [comment]
u could say i'm not @ f@n of it lmaoamoamlkaamoa

**Comment by clairebingham** [comment]
haha also this is issue #69

**Comment by spxrogers** [comment]
you're unbearable 
un :bear:able

**Comment by arrdem** [comment]
I love this response, so closing the issue but PRs will be merged as usual.
