### ISSUE TITLE
Issue with customer service

### ISSUE THREAD

**Issue by clairebingham** [TexasLAN/LANBot#70]
The customer service on this repo is terrible. They close very valid issues that the majority agrees with because a single person disagrees. Not how a business should be run. 1/5 starts on yelp

**Comment by clairebingham** [comment]
This is not issue #69

**Comment by arrdem** [comment]
I will merge literally anything.

The issue tracker represents my desires for what will be PR'd.

This is a statement of policy.

**Comment by stevendiaz** [comment]
Can I speak to ur manager

**Comment by arrdem** [comment]
I am the manager

bant
