### ISSUE TITLE
BRING BACK IMAGE ME 2016

### ISSUE THREAD

**Issue by stevendiaz** [TexasLAN/LANBot#89]
![screen shot 2016-01-20 at 10 47 26 pm](https://cloud.githubusercontent.com/assets/9388588/12471911/dce68156-bfc7-11e5-8b5e-d8bd2fcf4276.png)

**Comment by arrdem** [comment]
So some digging around on the official hubot bugtracker doesn't say anything about this. Worth checking if we're up to date in terms of used hubot shit. An option is switching to https://github.com/hubot-scripts/hubot-google-images or something which provides similar and working functionality.

**Comment by aaaanderson** [comment]
rt

**Comment by rob0rt** [comment]
It ain't dead, we just need a google API key. I tried to get one but I don't have the gmail login and I ain't lettin you all use mine.

**Comment by arrdem** [comment]
![2016-01-25-232433_464x286_scrot](https://cloud.githubusercontent.com/assets/704767/12573144/ce41c27c-c3ba-11e5-9df8-0374793ef7d2.png)
